SELECT 
    V.M_PRODUCT_ID, 
    V.MOVEMENTDATE,
    SUM(CASE WHEN V.MOVEMENTTYPE IN ('V+', 'P+') THEN V.MOVEMENTQTY ELSE NULL END) AS Receipt,
    SUM(CASE WHEN V.MOVEMENTTYPE = 'P-' THEN V.MOVEMENTQTY ELSE NULL END) AS Issue,
    MAX(MS.QTYONHAND) ONHAND,
    V.COSTAVERAGE
FROM M_Transaction_Detail_V V LEFT JOIN M_STORAGE MS on V.M_PRODUCT_ID = MS.M_PRODUCT_ID 
WHERE 
    V.M_PRODUCT_ID = 1120819
    AND V.M_WAREHOUSE_ID = 1000740
    AND V.M_LOCATOR_ID = 1006001
    AND V.M_PRODUCT_CATEGORY_ID = 1000907
    AND V.MOVEMENTDATE >= TO_DATE('01-FEB-2025', 'DD-MON-YYYY')
GROUP BY 
    V.M_PRODUCT_ID, V.MOVEMENTDATE, V.COSTAVERAGE
 

order by V.MOVEMENTDATE 

